name: terraform CI/CD Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - apply
          - destroy
          - plan
          - validate
          - refresh
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod




jobs:
  terraform:
    name: Infrastructure Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.56.3/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        working-directory: live/${{ github.event.inputs.environment }}
        run: terraform init


      - name: Run Terraform Task
        working-directory: live/${{ github.event.inputs.environment }}
        run: |
          case "${{ github.event.inputs.action }}" in
            plan)
              terraform plan -out=tfplan
              ;;
            apply)
              terraform apply -auto-approve tfplan
              ;;
            destroy)
              terraform destroy -auto-approve
              ;;
            validate)
              terraform validate
              ;;
            refresh)
              terraform refresh
              ;;
            *)
              echo "Unknown action: ${{ github.event.inputs.action }}"
              exit 1
              ;;
          esac


      
