name: terraform CI/CD Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - apply
          - destroy
          - plan
          - validate
          - refresh
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod




jobs:
  terraform:
    name: Infrastructure Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
          unzip terraform_1.6.6_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version


      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Terragrunt Task
        working-directory: live/${{ github.event.inputs.environment }}
        run: |
          case "${{ github.event.inputs.action }}" in
            init)
              terragrunt init --terragrunt-experimental-cli
              ;;
            plan)
              terragrunt plan --terragrunt-experimental-cli -out=tfplan
              ;;
            apply)
              terragrunt apply --auto-approve --terragrunt-experimental-cli tfplan
              ;;
            destroy)
              terragrunt destroy --auto-approve --terragrunt-experimental-cli
              ;;
            validate)
              terragrunt validate --terragrunt-experimental-cli
              ;;
            refresh)
              terragrunt refresh --terragrunt-experimental-cli
              ;;
            *)
              echo "Unknown action: ${{ github.event.inputs.action }}"
              exit 1
              ;;
          esac


      
